wandb_version: 1

env:
  desc: null
  value: JSSEnv:jss-v1
seed:
  desc: null
  value: 0
framework:
  desc: null
  value: torch
log_level:
  desc: null
  value: WARN
num_gpus:
  desc: null
  value: 0
instance_path:
  desc: null
  value: /home/aiden/ORNL/JSSEnv/JSS/JSS/instances/ta41
num_envs_per_worker:
  desc: null
  value: 2
rollout_fragment_length:
  desc: null
  value: 1024
num_workers:
  desc: null
  value: 19
sgd_minibatch_size:
  desc: null
  value: 256
evaluation_interval:
  desc: null
  value: null
metrics_smoothing_episodes:
  desc: null
  value: 1000
gamma:
  desc: null
  value: 1.0
layer_size:
  desc: null
  value: 1024
layer_nb:
  desc: null
  value: 2
lr:
  desc: null
  value: 7.0e-05
lr_schedule:
  desc: null
  value:
  - - 0
    - 7.0e-05
  - - 4000000
    - 3.0e-05
clip_param:
  desc: null
  value: 0.3
vf_clip_param:
  desc: null
  value: 10.0
kl_target:
  desc: null
  value: 0.01
num_sgd_iter:
  desc: null
  value: 25
lambda:
  desc: null
  value: 1.0
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
kl_coeff:
  desc: null
  value: 0.2
shuffle_sequences:
  desc: null
  value: true
vf_share_layers:
  desc: null
  value: false
vf_loss_coeff:
  desc: null
  value: 1.0
entropy_coeff:
  desc: null
  value: 0.0005
entropy_coeff_schedule:
  desc: null
  value: null
grad_clip:
  desc: null
  value: null
batch_mode:
  desc: null
  value: truncate_episodes
observation_filter:
  desc: null
  value: NoFilter
simple_optimizer:
  desc: null
  value: false
_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.17.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720018585
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.7.16
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
